heat_template_version: 2015-04-30

description: >
  HOT template to create a AliasIpPool:

parameters:
  name:
    type: string
    description: name for the AliasIpPool
    # required: optional
  fq_name:
    type: string
    description: fq_name for the AliasIpPool
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  project:
    type: string
    description: project for the VirtualNetwork
    # required: optional

resources:
  VirtualNetwork:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      project: { get_param: project }

  template_AliasIpPool:
    type: OS::ContrailV2::AliasIpPool
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      display_name: { get_param: display_name }
      virtual_network: { get_resource: VirtualNetwork }

