heat_template_version: 2015-04-30

description: >
  HOT template to create a AliasIp:

parameters:
  name:
    type: string
    description: name for the AliasIp
    # required: optional
  fq_name:
    type: string
    description: fq_name for the AliasIp
    # required: optional
  alias_ip_address:
    type: string
    description: Alias ip address.
    # operations: CR
    # required: required
  alias_ip_address_family:
    type: string
    description: Ip address family of the alias ip, IpV4 or IpV6
    # operations: CRUD
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  project_refs:
    type: string
    description: Reference to project from which this alias ip was allocated.
    # required: optional
  virtual_machine_interface_refs:
    type: string
    description: Reference to virtual machine interface to which this alias ip is attached.
    # required: optional
  network_ipam_refs:
    type: string
    description: Reference to network-ipam this network is using. It has list of subnets that are being used as
    # required: optional

resources:
  virtual_network:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      name: Something
      network_ipam_refs: [{ get_param: network_ipam_refs }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 10.0.0.0,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 24,
                },
              network_ipam_refs_data_ipam_subnets_subnet_name: Something,
            }],
        }]
      project: { get_param: project_refs }

  AliasIpPool:
    type: OS::ContrailV2::AliasIpPool
    properties:
      name: 'Something'
      virtual_network: { get_resource: virtual_network }

  template_AliasIp:
    type: OS::ContrailV2::AliasIp
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      alias_ip_address: { get_param: alias_ip_address }
      alias_ip_address_family: { get_param: alias_ip_address_family }
      display_name: { get_param: display_name }
      project_refs: [{ get_param: project_refs }]
      virtual_machine_interface_refs: [{ get_param: virtual_machine_interface_refs }]
      alias_ip_pool: { get_resource: AliasIpPool }
      # alias_ip_pool: { get_param: alias_ip_pool }

