heat_template_version: 2015-04-30

description: >
  HOT template to create a ApiAccessList:

parameters:
  name:
    type: string
    description: name for the ApiAccessList
    # required: optional
  fq_name:
    type: string
    description: fq_name for the ApiAccessList
    # required: optional
  api_access_list_entries_rbac_rule_rule_object:
    type: string
    description: Name of the REST API (object) for this rule, * represent all objects
    # operations: CRUD
    # required: true
  api_access_list_entries_rbac_rule_rule_field:
    type: string
    description: Name of the level one field (property) for this object, * represent all properties
    # operations: CRUD
    # required: optional
  api_access_list_entries_rbac_rule_rule_perms_role_name:
    type: string
    description: Name of the role
    # operations: CRUD
    # required: true
  api_access_list_entries_rbac_rule_rule_perms_role_crud:
    type: string
    description: String CRUD representing permissions for C=create, R=read, U=update, D=delete.
    # operations: CRUD
    # required: true
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  domain:
    type: string
    description: domain for the ApiAccessList
    # required: optional
  project:
    type: string
    description: project for the ApiAccessList
    # required: optional
  global_system_config:
    type: string
    description: global_system_config for the ApiAccessList
    # required: optional

resources:
  template_ApiAccessList:
    type: OS::ContrailV2::ApiAccessList
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      api_access_list_entries:
        {
          api_access_list_entries_rbac_rule:
            [{
              api_access_list_entries_rbac_rule_rule_object: { get_param: api_access_list_entries_rbac_rule_rule_object },
              api_access_list_entries_rbac_rule_rule_field: { get_param: api_access_list_entries_rbac_rule_rule_field },
              api_access_list_entries_rbac_rule_rule_perms:
                [{
                  api_access_list_entries_rbac_rule_rule_perms_role_name: { get_param: api_access_list_entries_rbac_rule_rule_perms_role_name },
                  api_access_list_entries_rbac_rule_rule_perms_role_crud: { get_param: api_access_list_entries_rbac_rule_rule_perms_role_crud },
                }],
            }],
        }
      display_name: { get_param: display_name }
      domain: { get_param: domain }
      project: { get_param: project }
      global_system_config: { get_param: global_system_config }

