heat_template_version: 2015-04-30

description: >
  HOT template to create a BgpAsAService:

parameters:
  name:
    type: string
    description: name for the BgpAsAService
    # required: optional
  fq_name:
    type: string
    description: fq_name for the BgpAsAService
    # required: optional
  bgpaas_session_attributes_bgp_router:
    type: string
    description: When the parameters are uni-directional the bgp-router element specifies to which node the configuration applies. If missing the attributes apply to both ends of the session.
    # operations: CRUD
    # required: optional
  bgpaas_session_attributes_admin_down:
    type: boolean
    description: Administratively mark this session down.
    # operations: CRUD
    # required: optional
  bgpaas_session_attributes_passive:
    type: boolean
    description: This is passive session. It will not initiated connection. This is not relavent when session attributes represent common part. It is recomended that it should not be set to true in current release.
    # operations: CRUD
    # required: optional
  bgpaas_session_attributes_as_override:
    type: boolean
    description: To Be Added
    # operations: CRUD
    # required: optional
  bgpaas_session_attributes_hold_time:
    type: number
    description: A non-zero hold-time overrides the hold-time inherited from the bgp-router configuration. BGP hold time in seconds [0-65535], Max time to detect liveliness of peer.
    # operations: CRUD
    # required: optional
  bgpaas_session_attributes_loop_count:
    type: number
    description: For routing loop detection, loop-count is the number of times the local bgp-routers AS is             allowed in the AS_PATH attribute.
    # operations: CRUD
    # required: optional
  bgpaas_session_attributes_address_families_family:
    type: string
    description: BGP address families supported by contrail.
    # operations: CRUD
    # required: optional
  bgpaas_session_attributes_auth_data_key_type:
    type: string
    description: Authentication type for this session. Currently only MD5 is supported.
    # operations: CRUD
    # required: true
  bgpaas_session_attributes_auth_data_key_items_key_id:
    type: number
    description: key_id for the BgpAsAService
    # operations: CRUD
    # required: optional
  bgpaas_session_attributes_auth_data_key_items_key:
    type: string
    description: key for the BgpAsAService
    # operations: CRUD
    # required: optional
  bgpaas_session_attributes_family_attributes_address_family:
    type: string
    description: Address family for which these parameters are applied.
    # operations: CRUD
    # required: true
  bgpaas_session_attributes_family_attributes_loop_count:
    type: number
    description: For routing loop detection, loop-count is the number of times the local bgp-routers AS is             allowed in the AS_PATH attribute.
    # operations: CRUD
    # required: optional
  bgpaas_session_attributes_family_attributes_prefix_limit_maximum:
    type: number
    description: maximum for the BgpAsAService
    # operations: CRUD
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  bgpaas_suppress_route_advertisement:
    type: boolean
    description: True when server should not advertise any routes to the client i.e. the client has static routes
    # operations: CRUD
    # required: optional
  bgpaas_ipv4_mapped_ipv6_nexthop:
    type: boolean
    description: True when client bgp implementation expects to receive a ipv4-mapped ipv6 address (as opposed to
    # operations: CRUD
    # required: optional
  bgpaas_ip_address:
    type: string
    description: Ip address of the BGP peer.
    # operations: CRUD
    # required: required
  autonomous_system:
    type: number
    description: 16 bit BGP Autonomous System number for the cluster.
    # operations: CRUD
    # required: required
  bgp_router_refs:
    type: string
    description: Reference to internal BGP peer object automatically generated by the system.
    # required: optional
  virtual_machine_interface_refs:
    type: string
    description: Reference to VMI on which BGPaaS BGP peering will happen.
    # required: optional
  project:
    type: string
    description: project for the BgpAsAService
    # required: optional

resources:
  template_BgpAsAService:
    type: OS::ContrailV2::BgpAsAService
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      bgpaas_session_attributes:
        {
          bgpaas_session_attributes_bgp_router: { get_param: bgpaas_session_attributes_bgp_router },
          bgpaas_session_attributes_admin_down: { get_param: bgpaas_session_attributes_admin_down },
          bgpaas_session_attributes_passive: { get_param: bgpaas_session_attributes_passive },
          bgpaas_session_attributes_as_override: { get_param: bgpaas_session_attributes_as_override },
          bgpaas_session_attributes_hold_time: { get_param: bgpaas_session_attributes_hold_time },
          bgpaas_session_attributes_loop_count: { get_param: bgpaas_session_attributes_loop_count },
          bgpaas_session_attributes_address_families:
            {
              bgpaas_session_attributes_address_families_family: [{ get_param: bgpaas_session_attributes_address_families_family }],
            },
          bgpaas_session_attributes_auth_data:
            {
              bgpaas_session_attributes_auth_data_key_type: { get_param: bgpaas_session_attributes_auth_data_key_type },
              bgpaas_session_attributes_auth_data_key_items:
                [{
                  bgpaas_session_attributes_auth_data_key_items_key_id: { get_param: bgpaas_session_attributes_auth_data_key_items_key_id },
                  bgpaas_session_attributes_auth_data_key_items_key: { get_param: bgpaas_session_attributes_auth_data_key_items_key },
                }],
            },
          bgpaas_session_attributes_family_attributes:
            [{
              bgpaas_session_attributes_family_attributes_address_family: { get_param: bgpaas_session_attributes_family_attributes_address_family },
              bgpaas_session_attributes_family_attributes_loop_count: { get_param: bgpaas_session_attributes_family_attributes_loop_count },
              bgpaas_session_attributes_family_attributes_prefix_limit:
                {
                  bgpaas_session_attributes_family_attributes_prefix_limit_maximum: { get_param: bgpaas_session_attributes_family_attributes_prefix_limit_maximum },
                },
            }],
        }
      display_name: { get_param: display_name }
      bgpaas_suppress_route_advertisement: { get_param: bgpaas_suppress_route_advertisement }
      bgpaas_ipv4_mapped_ipv6_nexthop: { get_param: bgpaas_ipv4_mapped_ipv6_nexthop }
      bgpaas_ip_address: { get_param: bgpaas_ip_address }
      autonomous_system: { get_param: autonomous_system }
      bgp_router_refs: [{ get_param: bgp_router_refs }]
      virtual_machine_interface_refs: [{ get_param: virtual_machine_interface_refs }]
      project: { get_param: project }

