heat_template_version: 2015-04-30

description: >
  HOT template to create a CustomerAttachment:

parameters:
  name:
    type: string
    description: name for the CustomerAttachment
    # required: optional
  fq_name:
    type: string
    description: fq_name for the CustomerAttachment
    # required: optional
  attachment_address:
    type: json
    description: attachment_address for the CustomerAttachment
    # operations: CRUD
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  project_refs:
    type: string
    description: Reference to project is which this floating ip was allocated.
    # required: optional

resources:
  NetworkIpam:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: Something
      project: { get_param: project_refs }

  VirtualNetwork:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      project: { get_param: project_refs }
      network_ipam_refs: [{ get_resource: NetworkIpam }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 10.0.0.0,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 24,
                },
            }],
        }]

  VirtualMachineInterface:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      virtual_network_refs: [{ get_resource: VirtualNetwork }]
      project: { get_param: project_refs }

  FloatingIpPool:
    type: OS::ContrailV2::FloatingIpPool
    properties:
      virtual_network: { get_resource: VirtualNetwork }

  FloatingIp:
    type: OS::ContrailV2::FloatingIp
    properties:
      floating_ip_pool: { get_resource: FloatingIpPool }
      project_refs: [{ get_param: project_refs }]

  template_CustomerAttachment:
    type: OS::ContrailV2::CustomerAttachment
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      attachment_address: { get_param: attachment_address }
      display_name: { get_param: display_name }
      floating_ip_refs: [{ get_resource: FloatingIp }]
      virtual_machine_interface_refs: [{ get_resource: VirtualMachineInterface }]

