heat_template_version: 2015-04-30

description: >
  HOT template to create a LoadbalancerHealthmonitor:

parameters:
  name:
    type: string
    description: name for the LoadbalancerHealthmonitor
    # required: optional
  fq_name:
    type: string
    description: fq_name for the LoadbalancerHealthmonitor
    # required: optional
  loadbalancer_healthmonitor_properties_admin_state:
    type: boolean
    description: Administratively up or dowm.
    # operations: CRUD
    # required: optional
  loadbalancer_healthmonitor_properties_monitor_type:
    type: string
    description: Protocol used to monitor health, PING, HTTP, HTTPS or TCP
    # operations: CRUD
    # required: true
  loadbalancer_healthmonitor_properties_delay:
    type: number
    description: Time in seconds  at which health check is repeated
    # operations: CRUD
    # required: true
  loadbalancer_healthmonitor_properties_timeout:
    type: number
    description: Time in seconds to wait for response
    # operations: CRUD
    # required: true
  loadbalancer_healthmonitor_properties_max_retries:
    type: number
    description: Number of failures before declaring health bad
    # operations: CRUD
    # required: true
  loadbalancer_healthmonitor_properties_http_method:
    type: string
    description: In case monitor protocol is HTTP, type of http method used like GET, PUT, POST etc
    # operations: CRUD
    # required: optional
  loadbalancer_healthmonitor_properties_url_path:
    type: string
    description: In case monitor protocol is HTTP, URL to be used. In case of ICMP, ip address
    # operations: CRUD
    # required: optional
  loadbalancer_healthmonitor_properties_expected_codes:
    type: string
    description: In case monitor protocol is HTTP, expected return code for HTTP operations like 200 ok.
    # operations: CRUD
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  project:
    type: string
    description: project for the LoadbalancerHealthmonitor
    # required: optional

resources:
  template_LoadbalancerHealthmonitor:
    type: OS::ContrailV2::LoadbalancerHealthmonitor
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      loadbalancer_healthmonitor_properties:
        {
          loadbalancer_healthmonitor_properties_admin_state: { get_param: loadbalancer_healthmonitor_properties_admin_state },
          loadbalancer_healthmonitor_properties_monitor_type: { get_param: loadbalancer_healthmonitor_properties_monitor_type },
          loadbalancer_healthmonitor_properties_delay: { get_param: loadbalancer_healthmonitor_properties_delay },
          loadbalancer_healthmonitor_properties_timeout: { get_param: loadbalancer_healthmonitor_properties_timeout },
          loadbalancer_healthmonitor_properties_max_retries: { get_param: loadbalancer_healthmonitor_properties_max_retries },
          loadbalancer_healthmonitor_properties_http_method: { get_param: loadbalancer_healthmonitor_properties_http_method },
          loadbalancer_healthmonitor_properties_url_path: { get_param: loadbalancer_healthmonitor_properties_url_path },
          loadbalancer_healthmonitor_properties_expected_codes: { get_param: loadbalancer_healthmonitor_properties_expected_codes },
        }
      display_name: { get_param: display_name }
      project: { get_param: project }

