heat_template_version: 2015-04-30

description: >
  HOT template to create a LogicalRouter:

parameters:
  name:
    type: string
    description: name for the LogicalRouter
    # required: optional
  fq_name:
    type: string
    description: fq_name for the LogicalRouter
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  configured_route_target_list_route_target:
    type: string
    description: route_target for the LogicalRouter
    # operations: CRUD
    # required: optional
  project:
    type: string
    description: project for the LogicalRouter
    # required: optional

resources:
  VirtualNetwork1:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      name: vn1
      project: { get_param: project }

  VirtualNetwork2:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      name: vn2
      project: { get_param: project }

  VirtualMachineInterface:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      virtual_network_refs: [{ get_resource: VirtualNetwork1 }]
      project: { get_param: project }

  ServiceInstance:
    type: OS::ContrailV2::ServiceInstance
    properties:
      project: { get_param: project }

  RouteTable:
    type: OS::ContrailV2::RouteTable
    properties:
      project: { get_param: project }

  RouteTarget:
    type: OS::ContrailV2::RouteTarget

  template_LogicalRouter:
    type: OS::ContrailV2::LogicalRouter
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      display_name: { get_param: display_name }
      configured_route_target_list:
        {
          configured_route_target_list_route_target: [{ get_param: configured_route_target_list_route_target }],
        }
      virtual_network_refs: [{ get_resource: VirtualNetwork2 }]
      service_instance_refs: [{ get_resource: ServiceInstance }]
      route_table_refs: [{ get_resource: RouteTable }]
      virtual_machine_interface_refs: [{ get_resource: VirtualMachineInterface }]
      route_target_refs: [{ get_resource: RouteTarget }]
      project: { get_param: project }

