heat_template_version: 2015-04-30

description: >
  HOT template to create a Namespace:

parameters:
  name:
    type: string
    description: name for the Namespace
    # required: optional
  fq_name:
    type: string
    description: fq_name for the Namespace
    # required: optional
  namespace_cidr_ip_prefix:
    type: string
    description: ip_prefix for the Namespace
    # operations: CRUD
    # required: optional
  namespace_cidr_ip_prefix_len:
    type: number
    description: ip_prefix_len for the Namespace
    # operations: CRUD
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  domain:
    type: string
    description: domain for the Namespace
    # required: optional

resources:
  template_Namespace:
    type: OS::ContrailV2::Namespace
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      namespace_cidr:
        {
          namespace_cidr_ip_prefix: { get_param: namespace_cidr_ip_prefix },
          namespace_cidr_ip_prefix_len: { get_param: namespace_cidr_ip_prefix_len },
        }
      display_name: { get_param: display_name }
      domain: { get_param: domain }

