heat_template_version: 2015-04-30

description: >
  HOT template to create a NetworkIpam:

parameters:
  name:
    type: string
    description: name for the NetworkIpam
    # required: optional
  fq_name:
    type: string
    description: fq_name for the NetworkIpam
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  ipam_subnet_method:
    type: string
    description: Subnet method configuration for ipam, user can configure user-defined, flat or auto.
    # operations: CRD
    # required: optional
  network_ipam_mgmt_ipam_method:
    type: string
    description: ipam_method for the NetworkIpam
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_ipam_dns_method:
    type: string
    description: ipam_dns_method for the NetworkIpam
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_ipam_dns_server_tenant_dns_server_address_ip_address:
    type: string
    description: ip_address for the NetworkIpam
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_ipam_dns_server_virtual_dns_server_name:
    type: string
    description: In case of virtual DNS server, name of virtual DNS server
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_name:
    type: string
    description: Name of the DHCP option
    # operations: CRUD
    # required: true
  network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value:
    type: string
    description: Encoded DHCP option value (decimal)
    # operations: CRUD
    # required: true
  network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value_bytes:
    type: string
    description: Value of the DHCP option to be copied byte by byte
    # operations: CRUD
    # required: true
  network_ipam_mgmt_cidr_block_ip_prefix:
    type: string
    description: ip_prefix for the NetworkIpam
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_cidr_block_ip_prefix_len:
    type: number
    description: ip_prefix_len for the NetworkIpam
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_host_routes_route_prefix:
    type: string
    description: Ip prefix/len format prefix
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_host_routes_route_next_hop:
    type: string
    description: Ip address or service instance name.
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_host_routes_route_next_hop_type:
    type: string
    description: next_hop_type for the NetworkIpam
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_host_routes_route_community_attributes_community_attribute:
    type: string
    description: community_attribute for the NetworkIpam
    # operations: CRUD
    # required: optional
  ipam_subnets_subnets_subnet_ip_prefix:
    type: string
    description: ip_prefix for the NetworkIpam
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_subnet_ip_prefix_len:
    type: number
    description: ip_prefix_len for the NetworkIpam
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_default_gateway:
    type: string
    description: default-gateway ip address in the subnet, if not provided one is auto generated by the system.
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_dns_server_address:
    type: string
    description: DNS server ip address in the subnet, if not provided one is auto generated by the system.
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_enable_dhcp:
    type: boolean
    description: Enable DHCP for the VM(s) in this subnet
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_dns_nameservers:
    type: string
    description: Tenant DNS servers ip address in tenant DNS method
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_allocation_pools_start:
    type: string
    description: start for the NetworkIpam
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_allocation_pools_end:
    type: string
    description: end for the NetworkIpam
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_addr_from_start:
    type: boolean
    description: Start address allocation from start or from end of address range.
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_dhcp_option_list_dhcp_option_dhcp_option_name:
    type: string
    description: Name of the DHCP option
    # operations: CRD
    # required: true
  ipam_subnets_subnets_dhcp_option_list_dhcp_option_dhcp_option_value:
    type: string
    description: Encoded DHCP option value (decimal)
    # operations: CRD
    # required: true
  ipam_subnets_subnets_dhcp_option_list_dhcp_option_dhcp_option_value_bytes:
    type: string
    description: Value of the DHCP option to be copied byte by byte
    # operations: CRD
    # required: true
  ipam_subnets_subnets_host_routes_route_prefix:
    type: string
    description: Ip prefix/len format prefix
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_host_routes_route_next_hop:
    type: string
    description: Ip address or service instance name.
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_host_routes_route_next_hop_type:
    type: string
    description: next_hop_type for the NetworkIpam
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_host_routes_route_community_attributes_community_attribute:
    type: string
    description: community_attribute for the NetworkIpam
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_subnet_name:
    type: string
    description: User provided name for this subnet
    # operations: CRD
    # required: optional
  ipam_subnets_subnets_alloc_unit:
    type: number
    description: allocation unit for this subnet to allocate bulk ip addresses
    # operations: CRD
    # required: optional
  project:
    type: string
    description: project for the NetworkIpam
    # required: optional
  domain:
    type: string
    description: domain for the VirtualDns
    # required: optional

resources:
  VirtualDns:
    type: OS::ContrailV2::VirtualDns
    properties:
      name: Something
      virtual_dns_data:
        {
          virtual_dns_data_domain_name: Something,
          virtual_dns_data_dynamic_records_from_client: True,
          virtual_dns_data_record_order: fixed,
          virtual_dns_data_default_ttl_seconds: 1,
          virtual_dns_data_next_virtual_dns: 8.8.8.8,
          virtual_dns_data_floating_ip_record: 'dashed-ip',
          virtual_dns_data_external_visible: True,
          virtual_dns_data_reverse_resolution: True,
        }
      domain: { get_param: domain }

  template_NetworkIpam:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      display_name: { get_param: display_name }
      ipam_subnet_method: { get_param: ipam_subnet_method }
      network_ipam_mgmt:
        {
          network_ipam_mgmt_ipam_method: { get_param: network_ipam_mgmt_ipam_method },
          network_ipam_mgmt_ipam_dns_method: { get_param: network_ipam_mgmt_ipam_dns_method },
          network_ipam_mgmt_ipam_dns_server:
            {
              network_ipam_mgmt_ipam_dns_server_tenant_dns_server_address:
                {
                  network_ipam_mgmt_ipam_dns_server_tenant_dns_server_address_ip_address: [{ get_param: network_ipam_mgmt_ipam_dns_server_tenant_dns_server_address_ip_address }],
                },
              network_ipam_mgmt_ipam_dns_server_virtual_dns_server_name: { get_param: network_ipam_mgmt_ipam_dns_server_virtual_dns_server_name },
            },
          network_ipam_mgmt_dhcp_option_list:
            {
              network_ipam_mgmt_dhcp_option_list_dhcp_option:
                [{
                  network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_name: { get_param: network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_name },
                  network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value: { get_param: network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value },
                  network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value_bytes: { get_param: network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value_bytes },
                }],
            },
          network_ipam_mgmt_cidr_block:
            {
              network_ipam_mgmt_cidr_block_ip_prefix: { get_param: network_ipam_mgmt_cidr_block_ip_prefix },
              network_ipam_mgmt_cidr_block_ip_prefix_len: { get_param: network_ipam_mgmt_cidr_block_ip_prefix_len },
            },
          network_ipam_mgmt_host_routes:
            {
              network_ipam_mgmt_host_routes_route:
                [{
                  network_ipam_mgmt_host_routes_route_prefix: { get_param: network_ipam_mgmt_host_routes_route_prefix },
                  network_ipam_mgmt_host_routes_route_next_hop: { get_param: network_ipam_mgmt_host_routes_route_next_hop },
                  network_ipam_mgmt_host_routes_route_next_hop_type: { get_param: network_ipam_mgmt_host_routes_route_next_hop_type },
                  network_ipam_mgmt_host_routes_route_community_attributes:
                    {
                      network_ipam_mgmt_host_routes_route_community_attributes_community_attribute: [{ get_param: network_ipam_mgmt_host_routes_route_community_attributes_community_attribute }],
                    },
                }],
            },
        }
      ipam_subnets:
        {
          ipam_subnets_subnets:
            [{
              ipam_subnets_subnets_subnet:
                {
                  ipam_subnets_subnets_subnet_ip_prefix: { get_param: ipam_subnets_subnets_subnet_ip_prefix },
                  ipam_subnets_subnets_subnet_ip_prefix_len: { get_param: ipam_subnets_subnets_subnet_ip_prefix_len },
                },
              ipam_subnets_subnets_default_gateway: { get_param: ipam_subnets_subnets_default_gateway },
              ipam_subnets_subnets_dns_server_address: { get_param: ipam_subnets_subnets_dns_server_address },
              ipam_subnets_subnets_enable_dhcp: { get_param: ipam_subnets_subnets_enable_dhcp },
              ipam_subnets_subnets_dns_nameservers: [{ get_param: ipam_subnets_subnets_dns_nameservers }],
              ipam_subnets_subnets_allocation_pools:
                [{
                  ipam_subnets_subnets_allocation_pools_start: { get_param: ipam_subnets_subnets_allocation_pools_start },
                  ipam_subnets_subnets_allocation_pools_end: { get_param: ipam_subnets_subnets_allocation_pools_end },
                }],
              ipam_subnets_subnets_addr_from_start: { get_param: ipam_subnets_subnets_addr_from_start },
              ipam_subnets_subnets_dhcp_option_list:
                {
                  ipam_subnets_subnets_dhcp_option_list_dhcp_option:
                    [{
                      ipam_subnets_subnets_dhcp_option_list_dhcp_option_dhcp_option_name: { get_param: ipam_subnets_subnets_dhcp_option_list_dhcp_option_dhcp_option_name },
                      ipam_subnets_subnets_dhcp_option_list_dhcp_option_dhcp_option_value: { get_param: ipam_subnets_subnets_dhcp_option_list_dhcp_option_dhcp_option_value },
                      ipam_subnets_subnets_dhcp_option_list_dhcp_option_dhcp_option_value_bytes: { get_param: ipam_subnets_subnets_dhcp_option_list_dhcp_option_dhcp_option_value_bytes },
                    }],
                },
              ipam_subnets_subnets_host_routes:
                {
                  ipam_subnets_subnets_host_routes_route:
                    [{
                      ipam_subnets_subnets_host_routes_route_prefix: { get_param: ipam_subnets_subnets_host_routes_route_prefix },
                      ipam_subnets_subnets_host_routes_route_next_hop: { get_param: ipam_subnets_subnets_host_routes_route_next_hop },
                      ipam_subnets_subnets_host_routes_route_next_hop_type: { get_param: ipam_subnets_subnets_host_routes_route_next_hop_type },
                      ipam_subnets_subnets_host_routes_route_community_attributes:
                        {
                          ipam_subnets_subnets_host_routes_route_community_attributes_community_attribute: [{ get_param: ipam_subnets_subnets_host_routes_route_community_attributes_community_attribute }],
                        },
                    }],
                },
              ipam_subnets_subnets_subnet_name: { get_param: ipam_subnets_subnets_subnet_name },
              ipam_subnets_subnets_alloc_unit: { get_param: ipam_subnets_subnets_alloc_unit },
            }],
        }
      virtual_dns_refs: [{ get_resource: VirtualDns }]
      project: { get_param: project }

