heat_template_version: 2015-04-30

description: >
  HOT template to create a PhysicalInterface:

parameters:
  name:
    type: string
    description: name for the PhysicalInterface
    # required: optional
  fq_name:
    type: string
    description: fq_name for the PhysicalInterface
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  global_system_config:
    type: string
    description: global_system_config for the PhysicalRouter

resources:
  PhysicalRouter:
    type: OS::ContrailV2::PhysicalRouter
    properties:
      name: Something
      global_system_config: { get_param: global_system_config }

  template_PhysicalInterface:
    type: OS::ContrailV2::PhysicalInterface
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      display_name: { get_param: display_name }
      physical_interface_refs: []
      physical_router: { get_resource: PhysicalRouter }

