heat_template_version: 2015-04-30

description: >
  HOT template to create a PortTuple:

parameters:
  name:
    type: string
    description: name for the PortTuple
    # required: optional
  fq_name:
    type: string
    description: fq_name for the PortTuple
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  project:
    type: string
    description: project for the ServiceInstance
    # required: optional

resources:
  ServiceInstance:
    type: OS::ContrailV2::ServiceInstance
    properties:
      name: Something
      project: { get_param: project }

  template_PortTuple:
    type: OS::ContrailV2::PortTuple
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      display_name: { get_param: display_name }
      service_instance: { get_resource: ServiceInstance }

