heat_template_version: 2015-04-30

description: >
  HOT template to create a Project:

parameters:
  name:
    type: string
    description: name for the Project
    # required: optional
  fq_name:
    type: string
    description: fq_name for the Project
    # required: optional
  alarm_enable:
    type: boolean
    description: Flag to enable/disable alarms configured under global-system-config. True, if not set.
    # operations: CRUD
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  quota_defaults:
    type: number
    description: Need to clarify
    # operations: CRUD
    # required: optional
  quota_floating_ip:
    type: number
    description: Maximum number of floating ips
    # operations: CRUD
    # required: optional
  quota_instance_ip:
    type: number
    description: Maximum number of instance ips
    # operations: CRUD
    # required: optional
  quota_virtual_machine_interface:
    type: number
    description: Maximum number of virtual machine interfaces
    # operations: CRUD
    # required: optional
  quota_virtual_network:
    type: number
    description: Maximum number of virtual networks
    # operations: CRUD
    # required: optional
  quota_virtual_router:
    type: number
    description: Maximum number of logical routers
    # operations: CRUD
    # required: optional
  quota_virtual_DNS:
    type: number
    description: Maximum number of virtual DNS servers
    # operations: CRUD
    # required: optional
  quota_virtual_DNS_record:
    type: number
    description: Maximum number of virtual DNS records
    # operations: CRUD
    # required: optional
  quota_bgp_router:
    type: number
    description: Maximum number of bgp routers
    # operations: CRUD
    # required: optional
  quota_network_ipam:
    type: number
    description: Maximum number of network IPAMs
    # operations: CRUD
    # required: optional
  quota_access_control_list:
    type: number
    description: Maximum number of access control lists
    # operations: CRUD
    # required: optional
  quota_network_policy:
    type: number
    description: Maximum number of network policies
    # operations: CRUD
    # required: optional
  quota_floating_ip_pool:
    type: number
    description: Maximum number of floating ip pools
    # operations: CRUD
    # required: optional
  quota_service_template:
    type: number
    description: Maximum number of service templates
    # operations: CRUD
    # required: optional
  quota_service_instance:
    type: number
    description: Maximum number of service instances
    # operations: CRUD
    # required: optional
  quota_logical_router:
    type: number
    description: Maximum number of logical routers
    # operations: CRUD
    # required: optional
  quota_security_group:
    type: number
    description: Maximum number of security groups
    # operations: CRUD
    # required: optional
  quota_security_group_rule:
    type: number
    description: Maximum number of security group rules
    # operations: CRUD
    # required: optional
  quota_subnet:
    type: number
    description: Maximum number of subnets
    # operations: CRUD
    # required: optional
  quota_global_vrouter_config:
    type: number
    description: Maximum number of global vrouter configs
    # operations: CRUD
    # required: optional
  quota_loadbalancer_pool:
    type: number
    description: Maximum number of loadbalancer pools
    # operations: CRUD
    # required: optional
  quota_loadbalancer_member:
    type: number
    description: Maximum number of loadbalancer member
    # operations: CRUD
    # required: optional
  quota_loadbalancer_healthmonitor:
    type: number
    description: Maximum number of loadbalancer health monitors
    # operations: CRUD
    # required: optional
  quota_virtual_ip:
    type: number
    description: Maximum number of virtual ips
    # operations: CRUD
    # required: optional
  namespace_refs_data_ip_prefix:
    type: string
    description: ip_prefix for the Project
    # required: optional
  namespace_refs_data_ip_prefix_len:
    type: number
    description: ip_prefix_len for the Project
    # required: optional
  domain:
    type: string
    description: domain for the Project
    # required: optional
  project:
    type: string
    description: project for the VirtualNetwork
    # required: optional

resources:
  Namespace:
    type: OS::ContrailV2::Namespace
    properties:
      domain: { get_param: domain }

  VirtualNetwork:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      project: { get_param: project }

  AliasIpPool:
    type: OS::ContrailV2::AliasIpPool
    properties:
      name: Something
      virtual_network: { get_resource: VirtualNetwork }

  FloatingIpPool:
    type: OS::ContrailV2::FloatingIpPool
    properties:
      virtual_network: { get_resource: VirtualNetwork }

  template_Project:
    type: OS::ContrailV2::Project
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      alarm_enable: { get_param: alarm_enable }
      display_name: { get_param: display_name }
      quota:
        {
          quota_defaults: { get_param: quota_defaults },
          quota_floating_ip: { get_param: quota_floating_ip },
          quota_instance_ip: { get_param: quota_instance_ip },
          quota_virtual_machine_interface: { get_param: quota_virtual_machine_interface },
          quota_virtual_network: { get_param: quota_virtual_network },
          quota_virtual_router: { get_param: quota_virtual_router },
          quota_virtual_dns: { get_param: quota_virtual_DNS },
          quota_virtual_dns_record: { get_param: quota_virtual_DNS_record },
          quota_bgp_router: { get_param: quota_bgp_router },
          quota_network_ipam: { get_param: quota_network_ipam },
          quota_access_control_list: { get_param: quota_access_control_list },
          quota_network_policy: { get_param: quota_network_policy },
          quota_floating_ip_pool: { get_param: quota_floating_ip_pool },
          quota_service_template: { get_param: quota_service_template },
          quota_service_instance: { get_param: quota_service_instance },
          quota_logical_router: { get_param: quota_logical_router },
          quota_security_group: { get_param: quota_security_group },
          quota_security_group_rule: { get_param: quota_security_group_rule },
          quota_subnet: { get_param: quota_subnet },
          quota_global_vrouter_config: { get_param: quota_global_vrouter_config },
          quota_loadbalancer_pool: { get_param: quota_loadbalancer_pool },
          quota_loadbalancer_member: { get_param: quota_loadbalancer_member },
          quota_loadbalancer_healthmonitor: { get_param: quota_loadbalancer_healthmonitor },
          quota_virtual_ip: { get_param: quota_virtual_ip },
        }
      namespace_refs: [{ get_resource: Namespace }]
      namespace_refs_data:
        [{
          namespace_refs_data_ip_prefix: { get_param: namespace_refs_data_ip_prefix },
          namespace_refs_data_ip_prefix_len: { get_param: namespace_refs_data_ip_prefix_len },
        }]
      floating_ip_pool_refs: [{ get_resource: FloatingIpPool }]
      alias_ip_pool_refs: [{ get_resource: AliasIpPool }]
      domain: { get_param: domain }

