heat_template_version: 2015-04-30

description: >
  HOT template to create a ProviderAttachment:

parameters:
  name:
    type: string
    description: name for the ProviderAttachment
    # required: optional
  fq_name:
    type: string
    description: fq_name for the ProviderAttachment
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional

resources:
  GlobalSystemConfig:
    type: OS::ContrailV2::GlobalSystemConfig

  VirtualMachine:
    type: OS::ContrailV2::VirtualMachine

  VirtualRouter:
    type: OS::ContrailV2::VirtualRouter
    properties:
      virtual_machine_refs: [{ get_resource: VirtualMachine }]
      global_system_config: { get_resource: GlobalSystemConfig }

  template_ProviderAttachment:
    type: OS::ContrailV2::ProviderAttachment
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      display_name: { get_param: display_name }
      virtual_router_refs: [{ get_resource: VirtualRouter }]

