heat_template_version: 2015-04-30

description: >
  HOT template to create a ProviderAttachment:

parameters:
  name:
    type: string
    description: name for the ProviderAttachment
    # required: optional
  fq_name:
    type: string
    description: fq_name for the ProviderAttachment
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  virtual_router_refs:
    type: string
    description: Not in Use.
    # required: optional

resources:
  template_ProviderAttachment:
    type: OS::ContrailV2::ProviderAttachment
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      display_name: { get_param: display_name }
      virtual_router_refs: [{ get_param: virtual_router_refs }]

