heat_template_version: 2015-04-30

description: >
  HOT template to create a QosQueue:

parameters:
  name:
    type: string
    description: name for the QosQueue
    # required: optional
  fq_name:
    type: string
    description: fq_name for the QosQueue
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  max_bandwidth:
    type: number
    description: Maximum bandwidth for this queue.
    # operations: CRUD
    # required: required
  min_bandwidth:
    type: number
    description: Minimum bandwidth for this queue.
    # operations: CRUD
    # required: required

resources:
  GlobalSystemConfig:
    type: OS::ContrailV2::GlobalSystemConfig

  GlobalQosConfig:
    type: OS::ContrailV2::GlobalQosConfig
    properties:
      name: Something
      global_system_config: { get_resource: GlobalSystemConfig }

  template_QosQueue:
    type: OS::ContrailV2::QosQueue
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      display_name: { get_param: display_name }
      max_bandwidth: { get_param: max_bandwidth }
      min_bandwidth: { get_param: min_bandwidth }
      global_qos_config: { get_resource: GlobalQosConfig }

