heat_template_version: 2015-04-30

description: >
  HOT template to create a Subnet:

parameters:
  name:
    type: string
    description: name for the Subnet
    # required: optional
  fq_name:
    type: string
    description: fq_name for the Subnet
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  subnet_ip_prefix_ip_prefix:
    type: string
    description: ip_prefix for the Subnet
    # operations: CRD
    # required: optional
  subnet_ip_prefix_ip_prefix_len:
    type: number
    description: ip_prefix_len for the Subnet
    # operations: CRD
    # required: optional
  project:
    type: string
    description: project for the VirtualNetwork
    # required: optional

resources:
  VirtualNetwork:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      project: { get_param: project }

  VirtualMachineInterface:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      virtual_network_refs: [{ get_resource: VirtualNetwork }]
      project: { get_param: project }

  template_Subnet:
    type: OS::ContrailV2::Subnet
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      display_name: { get_param: display_name }
      subnet_ip_prefix:
        {
          subnet_ip_prefix_ip_prefix: { get_param: subnet_ip_prefix_ip_prefix },
          subnet_ip_prefix_ip_prefix_len: { get_param: subnet_ip_prefix_ip_prefix_len },
        }
      virtual_machine_interface_refs: [{ get_resource: VirtualMachineInterface }]

